In [2]:

import tensorflow as tf
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tensorflow.keras import layers
import shutil
import random
from PIL import Image
import numpy as np
import logging
from tensorflow.python.client import device_lib
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tensorflow.keras import layers
import tensorflow_hub as hub
import shutil
import random
from PIL import Image
import pickle
import shutil
from sklearn.datasets import load_boston
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE
from sklearn.linear_model import RidgeCV, LassoCV, Ridge, Lasso


import logging
logger = tf.get_logger()
logger.setLevel(logging.ERROR)
print(tf.__version__)

2.8.0

In [4]:
X = pd.read_csv("train_features.csv.zip")
Y = pd.read_csv("train_labels.csv.zip")


print(X.shape)
print(Y.shape)

X

(100, 1002)
(100, 2)

,Id,smiles,feature_0000,feature_0001,feature_0002,feature_0003,feature_0004,feature_0005,feature_0006,feature_0007,...,feature_0990,feature_0991,feature_0992,feature_0993,feature_0994,feature_0995,feature_0996,feature_0997,feature_0998,feature_0999
0,50000,C1C=c2c3ccoc3c3c4ccccc4c(cc3c2=C1)-c1scc2ccsc12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,50001,c1cc([se]c1-c1sc(-c2cccc3nsnc23)c2nccnc12)-c1c...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,50002,[SiH2]1C=CC=C1c1cc2cnc3c(sc4ccc5c[nH]cc5c34)c2...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,50003,C1C=c2ccc3c4cocc4c4c([se]c5cc(-c6cccs6)c6nsnc6...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,50004,C1c(ccc1-c1sc(-c2nccc3nsnc23)c2ccoc12)-c1scc2c...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,50095,C1C=c2c(cc3oc4c5CC=Cc5c5c[nH]cc5c4c3c2=C1)-c1c...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,50096,C1C(=Cc2c1c1c(c3nsnc23)c2[nH]ccc2c2=C[SiH2]C=c...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,50097,c1scc2c1ccc1[nH]c3c4oc(cc4c4nsnc4c3c21)-c1ccccn1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,50098,[SiH2]1c2cc[nH]c2-c2oc3cc(-c4nccc5nsnc45)c4nsn...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,50099,[SiH2]1cc2c(ccc(-c3cccc4nsnc34)c2c1)-c1ccc(nc1...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
X = pd.read_csv("pretrain_features.csv.zip")
Y = pd.read_csv("pretrain_labels.csv.zip")

print(X.shape)
print(Y.shape)

Y = Y.sort_values(by='lumo_energy',ascending=False)

# X["feature_0001"].mean()
Y

(50000, 1002)
(50000, 2)

          Id  lumo_energy
23259  23259    -1.756738
24530  24530    -1.784155
9981    9981    -1.802277
42761  42761    -1.847798
37752  37752    -1.855744
...      ...          ...
35174  35174    -4.343658
2360    2360    -4.345778
42026  42026    -4.355105
8546    8546    -4.409507
13695  13695    -4.426165

[50000 rows x 2 columns]